/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/y7NK9Tgt9Kv
 */
import { Input } from "@/components/ui/input"
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"

export function nearby() {
  return (
    (<main className="bg-white">
      <header className="flex items-center justify-between mb-4">
        <h1 className="text-2xl font-bold">Nearby Gas Stations</h1>
        <form className="relative">
          <SearchIcon
            className="absolute left-2.5 top-2.5 h-4 w-4 text-gray-500 dark:text-gray-400" />
          <Input className="pl-8" placeholder="Search stations..." type="search" />
        </form>
      </header>
      <section className="flex flex-col md:flex-row gap-4 md:gap-6">
        <div className="flex-1">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Gas Station 1</CardTitle>
              <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-lg font-bold">1.2 miles</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Diesel: $2.89 | Gasoline: $2.59</p>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
              <CardTitle className="text-sm font-medium">Gas Station 2</CardTitle>
              <MapPinIcon className="w-4 h-4 text-gray-500 dark:text-gray-400" />
            </CardHeader>
            <CardContent>
              <div className="text-lg font-bold">2.5 miles</div>
              <p className="text-xs text-gray-500 dark:text-gray-400">Diesel: $2.99 | Gasoline: $2.69</p>
            </CardContent>
          </Card>
        </div>
        <div className="w-full md:w-1/2 h-64 md:h-auto rounded-lg overflow-hidden">
          <img
            alt="Map"
            className="object-cover w-full h-full"
            height={500}
            src="/placeholder.svg"
            style={{
              aspectRatio: "500/500",
              objectFit: "cover",
            }}
            width={500} />
        </div>
      </section>
    </main>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function MapPinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>)
  );
}
export default Component;